export default [
    {
        id: 1,
        title: "titulo1",
        desc: "desc1",
        imgShowCase: "pixels.png",
        githubLogo: "logo-github.svg",
        iconGoToPage: "logo-go-to-page.svg",
        githubLink: "https://github.com/gabyplasencia/pixels-for-kids",
        pageLink: "https://pixel4kids.netlify.app/",
        htmlLogo: "logo-html.svg",
        htmlAlt: "logo html",
        html: "HTML",
        cssLogo: "logo-css.svg",
        cssAlt: "logo css",
        css: "CSS",
        sassLogo: "logo-sass.svg",
        sassAlt: "logo sass",
        sass: "SASS",
        jsLogo: "logo-js.svg",
        jsAlt: "logo javascript",
        js: "JavaScript",
        figmaLogo: "logo-figma.svg",
        figmaAlt: "logo figma",
        figma: "Figma",
    },
    {
        id: 2,
        title: "titulo2",
        desc: "desc2",
        imgShowCase: "animated-portfolio.png",
        githubLogo: "logo-github.svg",
        iconGoToPage: "logo-go-to-page.svg",
        githubLink: "https://github.com/gabyplasencia/Portfolio",
        pageLink: "https://gabrielaplasencia.netlify.app/",
        htmlLogo: "logo-html.svg",
        htmlAlt: "logo html",
        html: "HTML",
        cssLogo: "logo-css.svg",
        cssAlt: "logo css",
        css: "CSS",
        sassLogo: "logo-sass.svg",
        sassAlt: "logo sass",
        sass: "SASS",
        jsLogo: "logo-js.svg",
        jsAlt: "logo javascript",
        js: "JavaScript",
        gsapLogo: "logo-gsap.svg",
        gsapAlt: "logo gsap",
        gsap: "GSAP",
        figmaLogo: "logo-figma.svg",
        figmaAlt: "logo figma",
        figma: "Figma",
    },
    {
        id: 3,
        title: "titulo3",
        desc: "desc3",
        imgShowCase: "calculator.png",
        githubLogo: "logo-github.svg",
        iconGoToPage: "logo-go-to-page.svg",
        githubLink: "https://github.com/gabyplasencia/Age-Calculator",
        pageLink: "https://agecalculator-fm.netlify.app/",
        htmlLogo: "logo-html.svg",
        htmlAlt: "logo html",
        html: "HTML",
        cssLogo: "logo-css.svg",
        cssAlt: "logo css",
        css: "CSS",
        sassLogo: "logo-sass.svg",
        sassAlt: "logo sass",
        sass: "SASS",
        jsLogo: "logo-js.svg",
        jsAlt: "logo javascript",
        js: "JavaScript",
    },
    {
        id: 4,
        title: "titulo4",
        desc: "desc4",
        imgShowCase: "space-travel.png",
        githubLogo: "logo-github.svg",
        iconGoToPage: "logo-go-to-page.svg",
        githubLink: "https://github.com/gabyplasencia/Space-Travel-Website",
        pageLink: "https://spacetravel-fm.netlify.app/",
        htmlLogo: "logo-html.svg",
        htmlAlt: "logo html",
        html: "HTML",
        cssLogo: "logo-css.svg",
        cssAlt: "logo css",
        css: "CSS",
        sassLogo: "logo-sass.svg",
        sassAlt: "logo sass",
        sass: "SASS",
        jsLogo: "logo-js.svg",
        jsAlt: "logo javascript",
        js: "JavaScript",
        splideLogo: "logo-splide.svg",
        splideAlt: "logo splide",
        splide: "Splide",
    },
    {
        id: 5,
        title: "titulo5",
        desc: "desc5",
        imgShowCase: "sm-dashboard.png",
        githubLogo: "logo-github.svg",
        iconGoToPage: "logo-go-to-page.svg",
        githubLink: "https://github.com/gabyplasencia/Social-media-dashboard",
        pageLink: "https://socialmediadashboard-fm.netlify.app/",
        htmlLogo: "logo-html.svg",
        htmlAlt: "logo html",
        html: "HTML",
        cssLogo: "logo-css.svg",
        cssAlt: "logo css",
        css: "CSS",
        sassLogo: "logo-sass.svg",
        sassAlt: "logo sass",
        sass: "SASS",
        jsLogo: "logo-js.svg",
        jsAlt: "logo javascript",
        js: "JavaScript",
    }
    
]